CREATE DATABASE QLDACT;
USE QLDACT;
CREATE TABLE DEAN(
TENDA VARCHAR(50),
MADA VARCHAR(50) NOT NULL,
DDIEM_DA VARCHAR(125) NOT NULL,
PHONG VARCHAR(125),
PRIMARY KEY (MADA)
);
CREATE TABLE NHANVIEN(
HONV VARCHAR(50),
TENLOT VARCHAR(50),
TENNV VARCHAR(50),
MANV VARCHAR(50) NOT NULL,
NGSINNH DATE,
DCHI VARCHAR(50),
PHAI VARCHAR(50),
LUONG INT,
MA_NQL VARCHAR(50),
PHG VARCHAR(125),
PRIMARY KEY (MANV)
);
CREATE TABLE PHONGBAN(
TENPHG VARCHAR(125),
MAPHG VARCHAR(50) NOT NULL,
TRPHG VARCHAR(125),
NG_NHANCHUC DATE,
PRIMARY KEY(MAPHG)
);
CREATE TABLE DIADIEM_PHG(
MAPHG VARCHAR(50) NOT NULL,
DIADIEM VARCHAR(125) NOT NULL,
PRIMARY KEY(DIADIEM, MAPHG), 
constraint FK_DIADIEM_PHGPHONGBAN FOREIGN KEY (MAPHG)
references PHONGBAN(MAPHG)
);
CREATE TABLE THANNHAN(
MANV VARCHAR(50) NOT NULL,
TENTN VARCHAR(125) NOT NULL,
PHAI VARCHAR(20),
NGSINH DATE,
QUANHE VARCHAR(125) NOT NULL,
PRIMARY KEY (TENTN, MANV),
constraint FK_THANNHANNHANVIEN FOREIGN KEY (MANV)
references NHANVIEN(MANV)
);
CREATE TABLE CONGVIEC(
MADA VARCHAR(50) NOT NULL,
STT INT NOT NULL,
TEN_CONG_VIEC VARCHAR(125),
PRIMARY KEY (MADA, STT),
constraint FK_CONGVIECDEAN FOREIGN KEY (MADA)
references DEAN(MADA)
);
CREATE TABLE PHANCONG(
MANV VARCHAR(50) NOT NULL,
MADA VARCHAR(50) NOT NULL,
STT INT NOT NULL,
THOIGIAN DATETIME,
PRIMARY KEY (MANV, MADA, STT),
constraint FK_PHANCONGNHANVIEN FOREIGN KEY (MANV)
references NHANVIEN(MANV),
constraint FK_PHANCONGDEAN FOREIGN KEY (MADA)
references DEAN(MADA)
);